### PR TITLE
fix: issue lowercase attribute values for email parts

### LINKED ISSUE #9: Email attributes can be issued capitalized
I think this is unwanted. 

1. In the case a requestor asks for a specific value of an attribute, the user cannot comply.
This is also fixable by marking an attribute case insensitive in the scheme.
2. It's not aesthetic to issue a card displaying "joHN.dOE@yaHOO.com" for example.

### PR DESCRIPTION
**Pull request by leonbotros**
fixes #9

### CODE REVIEW

File: src/main/java/foundation/privacybydesign/email/EmailRestApi.java [hunk 1]
```diff
@@ -134,7 +134,7 @@ public Response sendEmailToken(@FormParam("email") String emailAddress,
     public Response verifyEmailToken(@FormParam("token") String token) throws KeyManagementException {
         EmailConfiguration conf = EmailConfiguration.getInstance();
 
-        String emailAddress = signer.verifyToken(token);
+        String emailAddress = signer.verifyToken(token).toLowerCase();
```
Comment (ivard) [inline src/main/java/foundation/privacybydesign/email/EmailRestApi.java:137]: Maybe it is neat then to also lowercase the email address in the confirmation email to prevent inconsistencies there.

**Review by ivard — APPROVED** [review]
